export default {
  COLORS: {
    LIGHT_100: '#FFFFFF',
    LIGHT_200: "#FFFAF1",
    LIGHT_300: "#E1E1E6",
    LIGHT_400: "#C4C4CC",
    LIGHT_500: "#7C7C8A",
    LIGHT_600: "#76797B",
    LIGHT_700: "#4D585E",
    
    DARK_100: "#000405",
    DARK_200: "#00070A",
    DARK_300: "#000204",
    DARK_400: "#000A0F",
    DARK_500: "#000C12",
    DARK_600: "#00111A",
    DARK_700: "#001119",
    DARK_800: "#0D161B",
    DARK_900: "#0D1D25",
    DARK_1000: "#192227",

    TOMATO_100: "#750310",
    TOMATO_200: "#92000E",
    TOMATO_300: "#AB222E",
    TOMATO_400: "#AB4D55",

    CARROT_100: "#FBA94C",

    MINT_100: "#04D361",

    CAKE_200: "#82F3FF",

    CAKE_100: "#065E7C",
  },

  FONTS: {
    POPPINS: {
      100: {
        fontFamily: "Poppins",
        fontWeight: "500",
        fontSize: "14px",
        lineHeight: "24px",
        letterSpacing: "0%",
        textDecoration: "none",
        paragraphSpacing: "0px",
        textTransform: "none",
      },
      200: {
        fontFamily: "Poppins",
        fontWeight: "500",
        fontSize: "20px",
        lineHeight: "160%",
        letterSpacing: "0%",
        textDecoration: "none",
        paragraphSpacing: "0px",
        textTransform: "none",
      },
      300: {
        bold: {
          fontFamily: "Poppins",
          fontWeight: "700",
          fontSize: "24px",
          lineHeight: "140%",
          letterSpacing: "0%",
          textDecoration: "none",
          paragraphSpacing: "0px",
          textTransform: "none",
        },
        regular: {
          fontFamily: "Poppins",
          fontWeight: "100",
          fontSize: "24px",
          lineHeight: "140%",
          letterSpacing: "0%",
          textDecoration: "none",
          paragraphSpacing: "0px",
          textTransform: "none",
        },
      },
      400: {
        fontFamily: "'Poppins', sans-serif",
        fontWeight: "500",
        fontSize: "32px",
        lineHeight: "140%",
        letterSpacing: "0%",
        textDecoration: "none",
        paragraphSpacing: "0px",
        textTransform: "none",
      },
      500: {
        fontFamily: "Poppins",
        fontWeight: "500",
        fontSize: "40px",
        lineHeight: "140%",
        letterSpacing: "0%",
        textDecoration: "none",
        paragraphSpacing: "0px",
        textTransform: "none",
      },
    },

    ROBOTO: {
      smallest_regular: {
        fontFamily: "Roboto",
        fontWeight: "400",
        fontSize: "12px",
        lineHeight: "160%",
        letterSpacing: "0%",
        textDecoration: "none",
        paragraphSpacing: "0px",
        textTransform: "none",
      },
      smaller_regular: {
        fontFamily: "Roboto",
        fontWeight: "400",
        fontSize: "14px",
        lineHeight: "160%",
        letterSpacing: "0%",
        textDecoration: "none",
        paragraphSpacing: "0px",
        textTransform: "none",
      },
      smaller_bold: {
        fontFamily: "Roboto",
        fontWeight: "700",
        fontSize: "14px",
        lineHeight: "160%",
        letterSpacing: "0%",
        textDecoration: "none",
        paragraphSpacing: "0px",
        textTransform: "none",
      },
      small_regular: {
        fontFamily: "Roboto",
        fontWeight: "400",
        fontSize: "16px",
        lineHeight: "100%",
        letterSpacing: "0%",
        textDecoration: "none",
        paragraphSpacing: "0px",
        textTransform: "none",
      },
      small_spaced: {
        fontFamily: "Roboto",
        fontWeight: "400",
        fontSize: "16px",
        lineHeight: "160%",
        letterSpacing: "0%",
        textDecoration: "none",
        paragraphSpacing: "0px",
        textTransform: "none",
      },
      big_bold: {
        fontFamily: "Roboto",
        fontWeight: "700",
        fontSize: "20px",
        lineHeight: "160%",
        letterSpacing: "0%",
        textDecoration: "none",
        paragraphSpacing: "0px",
        textTransform: "none",
      },
      bigger_bold: {
        fontFamily: "Roboto",
        fontWeight: "700",
        fontSize: "24px",
        lineHeight: "auto",
        letterSpacing: "0%",
        textDecoration: "none",
        paragraphSpacing: "0px",
        textTransform: "none",
      },
      biggest_regular: {
        fontFamily: "Roboto",
        fontWeight: "400",
        fontSize: "32px",
        lineHeight: "160%",
        letterSpacing: "0%",
        textDecoration: "none",
        paragraphSpacing: "0px",
        textTransform: "none",
      },
      giant_bold: {
        fontFamily: "Roboto",
        fontWeight: "700",
        fontSize: "42px",
        lineHeight: "auto",
        letterSpacing: "0%",
        textDecoration: "none",
        paragraphSpacing: "0px",
        textTransform: "none",
      },
    },
  }

}